In [1]:
import pandas as pd

# Создаем DataFrame с данными из таблицы
data = {
    'ID': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
    'Имя': ['Иван', 'Ольга', 'Алексей', 'Мария', 'Сергей', 'Анна', 'Дмитрий', 'Елена', 'Виктор', 'Алиса',
             'Павел', 'Роман', 'Татьяна', 'Николай', 'Валерия', 'Григорий', 'Юлия', 'Степан', 'Василиса', 'Пустой'],
    'Возраст': [34.0, 27.0, 45.0, 38.0, 29.0, 50.0, 31.0, 40.0, 28.0, 33.0, 46.0, 37.0, 41.0, 25.0, 42.0, 49.0, 50.0, 30.0, 35.0, None],
    'Город': ['Москва', 'Санкт-Петербург', 'Казань', 'Новосибирск', 'Екатеринбург', 'Воронеж', 'Челябинск', 'Краснодар', 'Ростов-на-Дону', 'Уфа',
              'Омск', 'Пермь', 'Тюмень', 'Саратов', 'Самара', 'Волгоград', 'Барнаул', 'Иркутск', 'Хабаровск', 'Томск'],
    'Баланс на счете': [120000, 80000, 150000, 200000, 95000, 300000, 140000, 175000, 110000, 9800,
                        250000, 210000, 135000, 155000, 125000, 180000, 275000, 320000, 105000, 90000],
    'Кредитная история': ['Хорошая', 'Средняя', 'Плохая', 'Хорошая', 'Средняя', 'Отличная', 'Средняя', 'Хорошая', 'Плохая', 'Средняя',
                          'Средняя', 'Отличная', 'Средняя', 'Хорошая', 'Средняя', 'Плохая', 'Отличная', 'Хорошая', 'Средняя', 'Плохая']
}

df = pd.DataFrame(data)

# 1. Подсчет количества пропущенных значений в каждом столбце
null_counts = df.isna().sum()

# 2. Подсчет количества заполненных значений в каждом столбце
filled_counts = df.notna().sum()

# 3. Вывести строки, где нет пропущенных значений
rows_without_na = df[df.isna().sum(axis=1) == 0]

# Вывод результатов
print("Количество пропущенных значений в каждом столбце:")
print(null_counts)

print("\nКоличество заполненных значений в каждом столбце:")
print(filled_counts)

print("\nСтроки без пропущенных значений:")
print(rows_without_na)

Количество пропущенных значений в каждом столбце:
ID                   0
Имя                  0
Возраст              1
Город                0
Баланс на счете      0
Кредитная история    0
dtype: int64

Количество заполненных значений в каждом столбце:
ID                   20
Имя                  20
Возраст              19
Город                20
Баланс на счете      20
Кредитная история    20
dtype: int64

Строки без пропущенных значений:
    ID       Имя  Возраст            Город  Баланс на счете Кредитная история
0    1      Иван     34.0           Москва           120000           Хорошая
1    2     Ольга     27.0  Санкт-Петербург            80000           Средняя
2    3   Алексей     45.0           Казань           150000            Плохая
3    4     Мария     38.0      Новосибирск           200000           Хорошая
4    5    Сергей     29.0     Екатеринбург            95000           Средняя
5    6      Анна     50.0          Воронеж           300000          Отличная
6    7   Дмитрий     31.0        Челябинск           140000           Средняя
7    8     Елена     40.0        Краснодар           175000           Хорошая
8    9    Виктор     28.0   Ростов-на-Дону           110000            Плохая
9   10     Алиса     33.0              Уфа             9800           Средняя
10  11     Павел     46.0             Омск           250000           Средняя
11  12     Роман     37.0            Пермь           210000          Отличная
12  13   Татьяна     41.0           Тюмень           135000           Средняя
13  14   Николай     25.0          Саратов           155000           Хорошая
14  15   Валерия     42.0           Самара           125000           Средняя
15  16  Григорий     49.0        Волгоград           180000            Плохая
16  17      Юлия     50.0          Барнаул           275000          Отличная
17  18    Степан     30.0          Иркутск           320000           Хорошая
18  19  Василиса     35.0        Хабаровск           105000           Средняя